FS: dep FeatureSelection/
	python FeatureSelection/main.py

NMF: dep NMF/
	python NMF/main.py

PCA: dep PCA/
	python PCA/main_pca.py

SVD: dep SVD/
	python SVD/my_svd.py

dep: requirements.txt
	pip install --upgrade pip
	pip install -r requirements.txt --upgrade --timeout 300