SVM1: dep SVM/
	python SVM/main1.py

SVM2: dep SVM/
	python SVM/main2.py

SVM3: dep SVM/
	python SVM/main3.py

AB: dep Adaboost/
	python Adaboost/ensembleExercise.py

dep: requirements.txt
	pip install --upgrade pip
	pip install -r requirements.txt --upgrade --timeout 300