RLR: dep data main.py computeGradreg.py computeCostreg.py mapFeatures.py plotBoundary.py predict.py sigmoid.py
	python -W ignore main.py

dep: requirements.txt
	pip install --upgrade pip
	pip install -r requirements.txt --upgrade --timeout 300