NN: dep main.py
	python main.py

HW: dep data my_net.py run_eval.py
	python -W ignore run_eval.py

dep: requirements.txt
	pip install --upgrade pip
	pip install -r requirements.txt --upgrade --timeout 300